#!/bin/bash

set -euo pipefail

IMAGE=cdflow-docs.local

docker image build -t "${IMAGE}" .

docker container run --rm \
    -v $(pwd):/usr/local/app \
    "${IMAGE}" \
    bundle exec jekyll build
docker container run --rm \
    -v $(pwd):/usr/local/app \
    -p 4000:4000 \
    "${IMAGE}" \
    bundle exec jekyll serve \
        -w \
        --incremental \
        --force_polling \
        --host 0.0.0.0
